# Generated by Django 4.1.5 on 2023-02-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('use', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('img1', models.CharField(max_length=255)),
                ('img2', models.CharField(max_length=255)),
                ('img3', models.CharField(max_length=255)),
                ('vaqti', models.IntegerField(default=0)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('many', models.ManyToManyField(blank=True, to='backend.turi')),
            ],
        ),
    ]
